In [1]:
import torch
from config import BitformerConfig
from model_zoo import VisionBitformerForImageClassification
from metrics import compute_metrics_single_label_classification
from trainer import get_trainer
from data_zoo import get_vision_dataset, vision_collator
from utils import get_yaml

In [2]:
yaml_path = './yamls/vision/small.yaml'
args = get_yaml(yaml_path)

In [8]:
args['model_config']['bitnet'] = False
args['model_config']['is_causal'] = True

In [9]:
cfg = BitformerConfig(**args['model_config'], num_labels=args['general_config']['num_labels'])
model = VisionBitformerForImageClassification(config=cfg)
model.num_parameters() / 1e6

1.071644

In [10]:
data_path = 'mnist'
train_dataset, test_dataset = get_vision_dataset(data_path)

In [11]:
trainer = get_trainer(model=model,
                      train_dataset=train_dataset,
                      valid_dataset=test_dataset,
                      compute_metrics=compute_metrics_single_label_classification,
                      data_collator=vision_collator,
                      **args['training_args'])

In [15]:
from bitlinear import BitLinear

lin = BitLinear(12, 12)

test = torch.rand(12, 12)
lin(test)

tensor([[ 0.1105,  0.2897,  0.5705, -0.2297, -0.3336,  0.0675, -0.1340, -0.0376,
         -0.4814, -0.1389,  0.6262,  0.4089],
        [ 0.2094, -0.1778, -0.1056,  0.1357, -0.2432,  0.5042,  0.0404, -0.3510,
          0.3815, -0.6274, -0.5043,  0.1885],
        [ 0.0232,  0.2586,  0.2016,  0.1475, -0.1849, -0.1894,  0.2320,  0.3485,
         -0.3150,  0.4499,  0.2386,  0.2179],
        [ 0.3208,  0.2644,  0.8728, -0.1088, -0.0172, -0.4009, -0.4587, -0.4161,
         -0.1588, -0.0313,  0.3714,  0.1464],
        [ 0.4986, -0.2678,  0.2527, -0.0176, -0.1153,  0.1124, -0.2902, -0.1840,
         -0.4230,  0.3782,  0.2015, -0.2929],
        [ 0.4524, -0.7170, -0.4111, -0.0433, -0.1466,  0.4002, -0.6343, -0.5213,
         -0.0511,  0.0145, -0.9816, -0.3988],
        [ 0.4776, -0.4850, -0.0682,  0.4079,  0.4100,  0.1178,  0.6273, -0.3355,
          0.1423,  0.4747,  0.1159, -0.3719],
        [-0.2280,  0.3171,  0.2292,  0.4833,  0.2185, -0.6899,  0.0606,  0.0602,
         -0.1375, -0.0589,  0.

In [21]:
lin.binarize_weights()

TypeError: BitLinear.binarize_weights() missing 1 required positional argument: 'weights_gamma'

In [12]:
trainer.train()
trainer.evaluate()

  0%|          | 0/9380 [00:00<?, ?it/s]

Could not estimate the number of tokens of the input, floating-point operations will not be computed


{'loss': 1.0212, 'grad_norm': 1.5853161811828613, 'learning_rate': 0.0004900072000534774, 'epoch': 1.0}


  0%|          | 0/157 [00:00<?, ?it/s]

Checkpoint destination directory ./results\checkpoint-938 already exists and is non-empty. Saving will proceed but saved results may be invalid.


{'eval_loss': 0.4045952260494232, 'eval_f1': 0.8887720066014907, 'eval_precision': 0.8905850300103851, 'eval_recall': 0.8885, 'eval_accuracy': 0.8885, 'eval_runtime': 0.939, 'eval_samples_per_second': 10649.391, 'eval_steps_per_second': 167.195, 'epoch': 1.0}


KeyboardInterrupt: 

In [7]:
trainer.train()

  0%|          | 0/9380 [00:00<?, ?it/s]

Could not estimate the number of tokens of the input, floating-point operations will not be computed


{'loss': 1.5768, 'grad_norm': 6.464507102966309, 'learning_rate': 0.0004977113991447017, 'epoch': 0.53}


  0%|          | 0/157 [00:00<?, ?it/s]

Confusion Matrix:
[[ 877    0    6    1   24    7   22    1   41    1]
 [   0 1027   16   13    3   46    6    7   15    2]
 [  50    5  648   57   40   87   65    3   69    8]
 [   2    4  105  701   11   52    2   18   48   67]
 [  43    4   18    2  659    9    4    8  163   72]
 [  33   11   44   54   37  581   14    6   87   25]
 [  18    2   15    2    3    5  846    0   67    0]
 [   0   12    2   12   45   20    0  696    5  236]
 [  55    1   12   10   21   22   10    3  823   17]
 [   8    4    1    9  170    3    1   15   48  750]]
{'eval_loss': 0.7616570591926575, 'eval_f1': 0.7619962587705958, 'eval_precision': 0.7746075940242815, 'eval_recall': 0.7608, 'eval_accuracy': 0.7608, 'eval_runtime': 3.6155, 'eval_samples_per_second': 2765.841, 'eval_steps_per_second': 43.424, 'epoch': 1.0}
{'loss': 0.8529, 'grad_norm': 10.953009605407715, 'learning_rate': 0.0004884857252366847, 'epoch': 1.07}
{'loss': 0.6767, 'grad_norm': 20.91096305847168, 'learning_rate': 0.0004724434323532821

  0%|          | 0/157 [00:00<?, ?it/s]

Confusion Matrix:
[[ 805    0   11    2   28   34   29    5   59    7]
 [   0 1079    4    4    3   11    4   16   14    0]
 [  18   19  750  106   10   76   17   13   18    5]
 [   0    7   29  821    2   52    3   49   17   30]
 [  17    6    9    5  688   50    8   27   57  115]
 [   2   11   21   63   10  734   15   12   19    5]
 [   5    8   18    0   12   26  880    0    9    0]
 [   0   10    5   21   13   19    0  879    1   80]
 [  23    3    9   16   16   78   23    1  771   34]
 [   1    1    0   27   29   26    1   98   16  810]]
{'eval_loss': 0.5544259548187256, 'eval_f1': 0.8223033609959465, 'eval_precision': 0.8283879974033689, 'eval_recall': 0.8217, 'eval_accuracy': 0.8217, 'eval_runtime': 3.6611, 'eval_samples_per_second': 2731.41, 'eval_steps_per_second': 42.883, 'epoch': 2.0}
{'loss': 0.5864, 'grad_norm': 8.617034912109375, 'learning_rate': 0.00045004305610692587, 'epoch': 2.13}
{'loss': 0.492, 'grad_norm': 15.679028511047363, 'learning_rate': 0.00042192486471335583

  0%|          | 0/157 [00:00<?, ?it/s]

Confusion Matrix:
[[ 893    0   25    0    9    3   10    4   31    5]
 [   0 1108   13    2    1    2    3    2    3    1]
 [  11   11  948   18    4   26    7    4    2    1]
 [   0   10  146  780    2   32    1   25    6    8]
 [  22    3   30    8  722   20    8   24   57   88]
 [   8    3   64   33    3  748    9    3   15    6]
 [   4    2   15    2   10    6  909    0   10    0]
 [   0   14   36   15    9    8    0  857    3   86]
 [  34    5   11   21   17   24   20    1  807   34]
 [   5    1    5   21   23   17    0   62    8  867]]
{'eval_loss': 0.4066694974899292, 'eval_f1': 0.863750619304394, 'eval_precision': 0.8684244303991644, 'eval_recall': 0.8639, 'eval_accuracy': 0.8639, 'eval_runtime': 3.6374, 'eval_samples_per_second': 2749.242, 'eval_steps_per_second': 43.163, 'epoch': 3.0}
{'loss': 0.4436, 'grad_norm': 5.626135349273682, 'learning_rate': 0.00038889255825490053, 'epoch': 3.2}
{'loss': 0.3974, 'grad_norm': 5.975671291351318, 'learning_rate': 0.00035189029658340025,

  0%|          | 0/157 [00:00<?, ?it/s]

Confusion Matrix:
[[ 936    0    4    0   11    1    4    2   18    4]
 [   0 1120    5    2    1    0    5    0    2    0]
 [  16   14  922   54    3    4   13    3    3    0]
 [   1   31   32  893    3    2   12   30    3    3]
 [  18    5   12   11  853    7   21    8   13   34]
 [  15   15   79   79    7  641   29    4   14    9]
 [   8    3    8    1   14    1  915    0    8    0]
 [   0   11   16   39   19    0    0  863    4   76]
 [  45   15   10   27   21    8   34    5  796   13]
 [  10    8    2   14   77    7    1   29   13  848]]
{'eval_loss': 0.3845398724079132, 'eval_f1': 0.8775848509542602, 'eval_precision': 0.8816738631728249, 'eval_recall': 0.8787, 'eval_accuracy': 0.8787, 'eval_runtime': 3.6513, 'eval_samples_per_second': 2738.768, 'eval_steps_per_second': 42.999, 'epoch': 4.0}
{'loss': 0.3618, 'grad_norm': 5.224878787994385, 'learning_rate': 0.00031197571247243834, 'epoch': 4.26}
{'loss': 0.325, 'grad_norm': 9.919211387634277, 'learning_rate': 0.00027028968138185784

  0%|          | 0/157 [00:00<?, ?it/s]

Confusion Matrix:
[[ 932    0    5    0   16    1   16    2    7    1]
 [   0 1114    5    2    0    0    3    0   11    0]
 [   8   11  954   23    5    4    8    8    7    4]
 [   0   18   37  897    0   18    3   17    9   11]
 [  10    8   12    1  829    5   20    5   37   55]
 [   7    4   55   51   11  695   32    3   17   17]
 [   5    2    8    1    7    2  926    1    6    0]
 [   0   11    9   11   17    2    0  902    5   71]
 [  22    4   11   17    3   14   37    0  858    8]
 [   4    5    2   14   43    5    1   22   28  885]]
{'eval_loss': 0.3215293288230896, 'eval_f1': 0.8986272841009766, 'eval_precision': 0.9002846041239704, 'eval_recall': 0.8992, 'eval_accuracy': 0.8992, 'eval_runtime': 3.6957, 'eval_samples_per_second': 2705.867, 'eval_steps_per_second': 42.482, 'epoch': 5.0}
{'loss': 0.3149, 'grad_norm': 14.113794326782227, 'learning_rate': 0.00022802371190303695, 'epoch': 5.33}
{'loss': 0.301, 'grad_norm': 13.288413047790527, 'learning_rate': 0.000186385888961295

  0%|          | 0/157 [00:00<?, ?it/s]

Confusion Matrix:
[[ 957    0    1    0    2    4    7    1    7    1]
 [   0 1122    3    1    1    0    4    1    3    0]
 [  16   27  861   57    5   30    9   17    6    4]
 [   2   13   16  935    1   12    0   24    3    4]
 [  10    5    3    3  827   24   14    8   10   78]
 [   4    4    3   40    2  812    7    2   14    4]
 [   6    3    3    4    7    7  926    0    2    0]
 [   1    8   10   12   20    5    0  888    4   80]
 [  31    5    2   15    3   35   37    6  821   19]
 [  14    4    1    7   25   12    1   13   13  919]]
{'eval_loss': 0.2990776300430298, 'eval_f1': 0.9063381509815707, 'eval_precision': 0.9087926569387182, 'eval_recall': 0.9068, 'eval_accuracy': 0.9068, 'eval_runtime': 3.5378, 'eval_samples_per_second': 2826.646, 'eval_steps_per_second': 44.378, 'epoch': 6.0}
{'loss': 0.2858, 'grad_norm': 4.608861923217773, 'learning_rate': 0.0001465663432182349, 'epoch': 6.4}
{'loss': 0.2742, 'grad_norm': 9.254112243652344, 'learning_rate': 0.00010970323365940444,

  0%|          | 0/157 [00:00<?, ?it/s]

Confusion Matrix:
[[ 925    0    7    1   13    4    1    1   23    5]
 [   0 1112    3    5    0    3    4    4    3    1]
 [  10    8  886   80   11   15    5   14    2    1]
 [   0    8   12  945    1   21    0   17    3    3]
 [   2    3    6    3  815    6    7   21    7  112]
 [   2    4   14   50    8  775    2    3   19   15]
 [   5    2    2    4   23   11  899    0   11    1]
 [   0    9    8   20    6    2    0  914    1   68]
 [  15    5    2   35    9   16    8    3  855   26]
 [   5    2    1   18    9    5    0   20    5  944]]
{'eval_loss': 0.27679070830345154, 'eval_f1': 0.907416436375048, 'eval_precision': 0.9107548690543191, 'eval_recall': 0.907, 'eval_accuracy': 0.907, 'eval_runtime': 3.6525, 'eval_samples_per_second': 2737.86, 'eval_steps_per_second': 42.984, 'epoch': 7.0}
{'loss': 0.2604, 'grad_norm': 19.479860305786133, 'learning_rate': 7.685021568435078e-05, 'epoch': 7.46}
{'loss': 0.2514, 'grad_norm': 12.069538116455078, 'learning_rate': 4.894632455610773e-05, 

  0%|          | 0/157 [00:00<?, ?it/s]

Confusion Matrix:
[[ 943    0    6    0    5    5    4    1   13    3]
 [   0 1112    3    2    0    0    3    0   14    1]
 [  10   10  908   39    8   26    3   17   10    1]
 [   3    8   16  920    0   24    1   17   12    9]
 [   4    2    2    2  826   11    6   32   23   74]
 [   2    2    5   30    5  804    9    2   29    4]
 [   3    4    3    3   14   11  909    0   11    0]
 [   0    8    5   15    5    3    0  951    4   37]
 [  17    3    1    8    3   15    6    2  907   12]
 [   7    1    0   11   11   10    0   40   21  908]]
{'eval_loss': 0.26105132699012756, 'eval_f1': 0.9188035293363653, 'eval_precision': 0.9200859889091951, 'eval_recall': 0.9188, 'eval_accuracy': 0.9188, 'eval_runtime': 3.6244, 'eval_samples_per_second': 2759.085, 'eval_steps_per_second': 43.318, 'epoch': 8.0}
{'loss': 0.2416, 'grad_norm': 8.064125061035156, 'learning_rate': 2.6789135029152173e-05, 'epoch': 8.53}


  0%|          | 0/157 [00:00<?, ?it/s]

Confusion Matrix:
[[ 925    0    4    0    9    4    8    2   21    7]
 [   0 1116    2    1    1    4    5    0    6    0]
 [   8   11  944   23    6   19    5   10    5    1]
 [   1    9   16  943    0   24    0   10    5    2]
 [   3    3    7    3  875   13   11    6   19   42]
 [   5    2    8   27    2  824    5    1   12    6]
 [   4    2    2    4   10    9  920    0    7    0]
 [   0   15   14   13   21    2    0  900    6   57]
 [  12    4    4   17    2   22    9    0  900    4]
 [   6    4    1   14   30   12    0   12   16  914]]
{'eval_loss': 0.242593914270401, 'eval_f1': 0.9260794668701173, 'eval_precision': 0.9267383853604548, 'eval_recall': 0.9261, 'eval_accuracy': 0.9261, 'eval_runtime': 3.6315, 'eval_samples_per_second': 2753.698, 'eval_steps_per_second': 43.233, 'epoch': 9.0}
{'loss': 0.2442, 'grad_norm': 4.718122959136963, 'learning_rate': 1.1011964332097113e-05, 'epoch': 9.06}
{'loss': 0.2297, 'grad_norm': 4.965157985687256, 'learning_rate': 2.065770110498438e-06,

  0%|          | 0/157 [00:00<?, ?it/s]

Confusion Matrix:
[[ 944    0    5    0    6    3    7    2   12    1]
 [   0 1119    3    2    0    1    4    0    6    0]
 [   8    9  968   20    2   11    4    8    2    0]
 [   2    8   21  949    0   12    1   10    4    3]
 [   2    5   11    2  897   10   12    7   10   26]
 [   3    3   15   35    2  808    8    1   12    5]
 [   5    2    6    2    8    6  922    0    7    0]
 [   0   15   16    9   18    2    0  919    5   44]
 [  23    3    5   22    6   18    9    0  882    6]
 [   8    3    4   15   57    9    0   22   14  877]]
{'eval_loss': 0.23178459703922272, 'eval_f1': 0.9282962114422455, 'eval_precision': 0.9285663043775354, 'eval_recall': 0.9285, 'eval_accuracy': 0.9285, 'eval_runtime': 3.5961, 'eval_samples_per_second': 2780.803, 'eval_steps_per_second': 43.659, 'epoch': 10.0}
{'train_runtime': 340.4996, 'train_samples_per_second': 1762.117, 'train_steps_per_second': 27.548, 'train_loss': 0.44155973503584545, 'epoch': 10.0}


TrainOutput(global_step=9380, training_loss=0.44155973503584545, metrics={'train_runtime': 340.4996, 'train_samples_per_second': 1762.117, 'train_steps_per_second': 27.548, 'train_loss': 0.44155973503584545, 'epoch': 10.0})

In [8]:
trainer.evaluate()

  0%|          | 0/157 [00:00<?, ?it/s]

Confusion Matrix:
[[ 944    0    5    0    6    3    7    2   12    1]
 [   0 1119    3    2    0    1    4    0    6    0]
 [   8    9  968   20    2   11    4    8    2    0]
 [   2    8   21  949    0   12    1   10    4    3]
 [   2    5   11    2  897   10   12    7   10   26]
 [   3    3   15   35    2  808    8    1   12    5]
 [   5    2    6    2    8    6  922    0    7    0]
 [   0   15   16    9   18    2    0  919    5   44]
 [  23    3    5   22    6   18    9    0  882    6]
 [   8    3    4   15   57    9    0   22   14  877]]


{'eval_loss': 0.23178459703922272,
 'eval_f1': 0.9282962114422455,
 'eval_precision': 0.9285663043775354,
 'eval_recall': 0.9285,
 'eval_accuracy': 0.9285,
 'eval_runtime': 3.4166,
 'eval_samples_per_second': 2926.901,
 'eval_steps_per_second': 45.952,
 'epoch': 10.0}

In [6]:
import torch
from torch import nn
from torchvision import transforms, datasets
from bitlinear import BitLinear as Linear

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
input_size = 784
hidden_size = 100
num_classes = 10
learning_rate = 0.001
num_epochs = 5


train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=64, shuffle=False)


class Net(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(Net, self).__init__()
        self.fc1 = Linear(input_size, hidden_size)
        self.fc2 = Linear(hidden_size, num_classes)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.log_softmax(self.fc2(x), dim=1)
        return x


# Create the model and optimizer
model = Net(input_size, hidden_size, num_classes)
model = model.to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=0.00001)
criterion = nn.NLLLoss()

# Train the model
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):
        # Forward pass
        outputs = model(images.view(-1, 28 * 28).to(device)).cpu()
        loss = criterion(outputs, labels)

        # Backward pass and optimize
        optimizer.zero_grad()
        loss.backward(retain_graph=False)
        optimizer.step()

        # Print training information
        if (i + 1) % 100 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}], Step [{i+1}/{len(train_loader)}], Loss: {loss.item():.4f}')

Epoch [1/5], Step [100/938], Loss: 2.1903
Epoch [1/5], Step [200/938], Loss: 2.0577
Epoch [1/5], Step [300/938], Loss: 1.9495
Epoch [1/5], Step [400/938], Loss: 1.8025
Epoch [1/5], Step [500/938], Loss: 1.6161
Epoch [1/5], Step [600/938], Loss: 1.5318
Epoch [1/5], Step [700/938], Loss: 1.4546
Epoch [1/5], Step [800/938], Loss: 1.3805
Epoch [1/5], Step [900/938], Loss: 1.2134
Epoch [2/5], Step [100/938], Loss: 1.2599
Epoch [2/5], Step [200/938], Loss: 1.0751
Epoch [2/5], Step [300/938], Loss: 1.2669
Epoch [2/5], Step [400/938], Loss: 1.0585
Epoch [2/5], Step [500/938], Loss: 1.0870
Epoch [2/5], Step [600/938], Loss: 0.9355
Epoch [2/5], Step [700/938], Loss: 0.9594
Epoch [2/5], Step [800/938], Loss: 0.9366
Epoch [2/5], Step [900/938], Loss: 0.9701
Epoch [3/5], Step [100/938], Loss: 0.9047
Epoch [3/5], Step [200/938], Loss: 0.7651
Epoch [3/5], Step [300/938], Loss: 0.8008
Epoch [3/5], Step [400/938], Loss: 0.7867
Epoch [3/5], Step [500/938], Loss: 0.8615
Epoch [3/5], Step [600/938], Loss:

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper_CUDA__native_layer_norm)

In [8]:
# Test the model
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in test_loader:
        outputs = model(images.view(-1, 28 * 28).to(device)).cpu()
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    print(f'Accuracy of the network on the 10000 test images: {100 * correct / total:.2f}%')

Accuracy of the network on the 10000 test images: 89.72%
